version: '3.0'

services:
  pmm:
    image: percona/pmm-server:2
    volumes:
    - pmm_srv:/srv
    ports:
    - 80:80
    - 443:443
  proxysql:
    image: percona/proxysql
    ports:
    - 6033:6033
    - 6032:6032
    volumes:
    - ./proxysql.cnf:/etc/proxysql/proxysql.cnf

volumes:
  pmm_srv: {}
