version: '3.0'

services:
  pmm:
    image: percona/pmm-server:2
    volumes:
    - pmm_srv:/srv
    ports:
    - 443:443
  proxysql:
    image: docker pull percona/proxysql
    ports:
    - 6032:6032

volumes:
  pmm_srv: {}
